"""empty message

Revision ID: 474ab964f788
Revises: ce44177dabfe
Create Date: 2024-11-27 05:44:33.086165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474ab964f788'
down_revision = 'ce44177dabfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_location_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type', sa.Enum('TEMPERATURE', 'HUMIDITY', 'SOIL_MOISTURE', 'SOIL_PH', 'RAINFALL', 'SOLAR_RADIATION', 'WIND_SPEED', 'SOIL_TEMPERATURE', 'SOIL_CONDUCTIVITY', 'SOIL_SALINITY', name='measurementtype'), nullable=False),
    sa.Column('unit', sa.Enum('CELSIUS', 'FAHRENHEIT', 'PERCENT', 'MILLIMETERS', 'INCHES', 'WATTS_PER_SQM', 'METERS_PER_SEC', 'KILOMETERS_PER_HOUR', 'MILES_PER_HOUR', 'PH', 'MICROSIEMENS', 'PPM', name='measurementunit'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('period_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['garden_location_id'], ['garden_locations.id'], name='fk_measurements_garden_location'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
