"""Add irrigation garden foreign key with named constraint

Revision ID: 9cd38f6782dd
Revises: 7e5e21b3a1ed
Create Date: 2024-10-27 05:13:32.287539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd38f6782dd'
down_revision = '7e5e21b3a1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_locations', schema=None) as batch_op:
        # Add the column with a default value
        batch_op.add_column(sa.Column('irrigation_zone_id', sa.Integer(), nullable=True, server_default='1'))
    
    # Update existing rows to have the default value
    op.execute('UPDATE garden_locations SET irrigation_zone_id = 1 WHERE irrigation_zone_id IS NULL')
    
    with op.batch_alter_table('garden_locations', schema=None) as batch_op:
        # Alter the column to be NOT NULL
        batch_op.alter_column('irrigation_zone_id', nullable=False, server_default=None)
        
        # Create the foreign key constraint
        batch_op.create_foreign_key('fk_garden_locations_irrigation_zone', 'irrigation_zones', ['irrigation_zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_garden_locations_irrigation_zone', type_='foreignkey')
        batch_op.drop_column('irrigation_zone_id')

    # ### end Alembic commands ###
