"""Initial Migration

Revision ID: c7295c45c5c7
Revises: 
Create Date: 2024-10-26 05:14:34.132076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7295c45c5c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('sun_exposure', sa.Enum('FULL', 'PARTIAL_SUN', 'PARTIAL_SHADE', 'DAPPLED', 'FULL_SHADE', name='sunexposure'), nullable=False),
    sa.Column('wind_exposure', sa.Enum('EXPOSED', 'PARTIALLY_EXPOSED', 'PROTECTED', 'INDOOR', name='windexposure'), nullable=False),
    sa.Column('drainage', sa.Enum('EXCELLENT', 'GOOD', 'POOR', name='drainage'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garden_locations')
    # ### end Alembic commands ###
