"""Add plant table

Revision ID: e8175e4ff2b4
Revises: 9cd38f6782dd
Create Date: 2024-10-29 06:19:16.195397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8175e4ff2b4'
down_revision = '9cd38f6782dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('growth_form', sa.Enum('TREE', 'SHRUB', 'VINE', 'HERB', 'GRASS', 'FERN', 'GROUNDCOVER', name='growthform'), nullable=False),
    sa.Column('life_cycle', sa.Enum('ANNUAL', 'BIENNIAL', 'PERENNIAL', 'EPHEMERAL', name='lifecycle'), nullable=False),
    sa.Column('primary_use', sa.Enum('ORNAMENTAL', 'VEGETABLE', 'FRUIT', 'HERB_CULINARY', 'HERB_MEDICINAL', 'GROUND_COVER', 'SHADE', 'PRIVACY', 'NATIVE_HABITAT', 'POLLINATOR', name='usecategory'), nullable=False),
    sa.Column('secondary_use', sa.Enum('ORNAMENTAL', 'VEGETABLE', 'FRUIT', 'HERB_CULINARY', 'HERB_MEDICINAL', 'GROUND_COVER', 'SHADE', 'PRIVACY', 'NATIVE_HABITAT', 'POLLINATOR', name='usecategory'), nullable=True),
    sa.Column('expected_height_inches', sa.Integer(), nullable=True),
    sa.Column('expected_spread_inches', sa.Integer(), nullable=True),
    sa.Column('hardiness_zone_min', sa.Integer(), nullable=True),
    sa.Column('hardiness_zone_max', sa.Integer(), nullable=True),
    sa.Column('preferred_soil_ph_min', sa.Float(), nullable=True),
    sa.Column('preferred_soil_ph_max', sa.Float(), nullable=True),
    sa.Column('planting_depth_inches', sa.Float(), nullable=True),
    sa.Column('spacing_inches', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['garden_location_id'], ['garden_locations.id'], name='fk_plants_garden_location'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
